In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('cars.csv')
df.tail(10)

brand  km_driven    fuel                 owner  selling_price
8118  Hyundai      25000  Petrol           First Owner         380000
8119   Maruti      80000  Petrol           First Owner         360000
8120  Hyundai     191000  Petrol           First Owner         120000
8121   Maruti      50000  Petrol          Second Owner         260000
8122  Hyundai      80000  Diesel          Second Owner         475000
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

In [3]:
from sklearn.preprocessing import OneHotEncoder  #nominal data ke liye

In [4]:
OHE=OneHotEncoder(sparse_output=False,dtype='int32',handle_unknown='ignore') #object 

# sparse_output=False: The output will be a regular array, not a compressed one (sparse_matrix 0&1 matrix).
# dtype='int32': The data will be stored as 32-bit integers (a smaller, efficient number type).
# handle_unknown='ignore': If there are unknown values during encoding, they will be ignored, not causing errors.


In [5]:
own=OHE.fit_transform(df[['owner']])


In [7]:
own #owner coloum encoding---> 4 values hence 4 columns in owner coloum
#Not directly like Ordinal encoder 0 1 2 3 Because the data is not in order form 
# Hence nominal data we use One hot encoder

array([[1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       ...,
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]], dtype=int32)

In [8]:
pd.DataFrame(own,columns=['First Owner', 'Second Owner', 'Third Owner',
                          'Fourth & Above Owner', 'Test Drive Car'])
# Creates a DataFrame (a table of data) using the own data, with the specified column names.

First Owner  Second Owner  Third Owner  Fourth & Above Owner  \
0               1             0            0                     0   
1               0             0            1                     0   
2               0             0            0                     0   
3               1             0            0                     0   
4               1             0            0                     0   
...           ...           ...          ...                   ...   
8123            1             0            0                     0   
8124            0             1            0                     0   
8125            1             0            0                     0   
8126            1             0            0                     0   
8127            1             0            0                     0   

      Test Drive Car  
0                  0  
1                  0  
2                  1  
3                  0  
4                  0  
...              ...  
8123               0  
8124               0  
8125               0  
8126               0  
8127               0  

[8128 rows x 5 columns]

In [9]:
x_train=[['satosa'],['verginica'],['versicolor']]
x_test=[['satosa'],['verginica'],['flower']]            #data frame data set
#x_test=[['satosa'],['verginica'],['versicolor']]  
# If we change xtest the mathematical encoding also changes as seen below                                              

In [10]:
OHE.fit(x_train)  #training

OneHotEncoder(dtype='int32', handle_unknown='ignore', sparse_output=False)

In [11]:
x_train=OHE.transform(x_train)
x_test=OHE.transform(x_test)        # transforming---->one hot encoding(nominal data)

In [12]:
x_train

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [13]:
x_test    

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]], dtype=int32)

In [14]:
pd.get_dummies(df,columns=['fuel','owner'])
#pd.get_dummies() is a function in pandas that converts categorical data (like text or categories) 
# into a format that can be used in machine learning models. It creates "dummy" or "one-hot" encoded variables,
#  where each category is represented by a separate column containing 0s and 1s.

# It turns categories into numbers.
# Each category gets its own column with a 0 or 1 value.

brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000     False         True     False   
1       Skoda     120000         370000     False         True     False   
2       Honda     140000         158000     False        False     False   
3     Hyundai     127000         225000     False         True     False   
4      Maruti     120000         130000     False        False     False   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000     False        False     False   
8124  Hyundai     119000         135000     False         True     False   
8125   Maruti     120000         382000     False         True     False   
8126     Tata      25000         290000     False         True     False   
8127     Tata      25000         290000     False         True     False   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0           False               True                       False   
1           False              False                       False   
2            True              False                       False   
3           False               True                       False   
4            True               True                       False   
...           ...                ...                         ...   
8123         True               True                       False   
8124        False              False                        True   
8125        False               True                       False   
8126        False               True                       False   
8127        False               True                       False   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                  False                 False              False  
1                   True                 False              False  
2                  False                 False               True  
3                  False                 False              False  
4                  False                 False              False  
...                  ...                   ...                ...  
8123               False                 False              False  
8124               False                 False              False  
8125               False                 False              False  
8126               False                 False              False  
8127               False                 False              False  

[8128 rows x 12 columns]

In [15]:
df['brand'].nunique()  #gives' actual number count of that particular column variable ie= 32 brands in a dataset
#df['brand'].unique()   # imp function

32